import type { Destino } from "./types";

// Dataset de demostración. En producción esto vendría de un servicio de
// contenidos/destinos actualizado, no de una lista estática.
export const DESTINOS: Destino[] = [
  {
    id: "eslovenia",
    nombre: "Eslovenia",
    pais: "Eslovenia",
    paisCodigo: "SI",
    descripcion: "Lagos, montañas y pueblos tranquilos a distancias muy cortas entre sí.",
    tags: ["naturaleza", "pueblos", "montana", "tranquilo", "lagos"],
    ritmo: ["tranquilo", "medio"],
    presupuestoDiaEstimado: { bajo: 60, medio: 100, alto: 180 },
    mascotaFriendly: true,
    distanciaConduccionCorta: true,
    climaCalido: false,
  },
  {
    id: "austria",
    nombre: "Austria",
    pais: "Austria",
    paisCodigo: "AT",
    descripcion: "Alpes, pueblos alpinos y ciudades con vida cultural intensa.",
    tags: ["naturaleza", "pueblos", "montana", "ciudad", "gastronomia"],
    ritmo: ["tranquilo", "medio", "intenso"],
    presupuestoDiaEstimado: { bajo: 80, medio: 140, alto: 240 },
    mascotaFriendly: true,
    distanciaConduccionCorta: true,
    climaCalido: false,
  },
  {
    id: "sur-alemania",
    nombre: "Sur de Alemania (Baviera)",
    pais: "Alemania",
    paisCodigo: "DE",
    descripcion: "Castillos, bosques y pueblos tradicionales con muy buena red de tren.",
    tags: ["naturaleza", "pueblos", "montana", "tranquilo"],
    ritmo: ["tranquilo", "medio"],
    presupuestoDiaEstimado: { bajo: 75, medio: 130, alto: 220 },
    mascotaFriendly: true,
    distanciaConduccionCorta: true,
    climaCalido: false,
  },
  {
    id: "algarve",
    nombre: "Algarve",
    pais: "Portugal",
    paisCodigo: "PT",
    descripcion: "Playas, acantilados, pueblos de pescadores y muy buena gastronomía.",
    tags: ["playa", "gastronomia", "pueblos", "romantico", "tranquilo"],
    ritmo: ["tranquilo", "medio"],
    presupuestoDiaEstimado: { bajo: 55, medio: 95, alto: 170 },
    mascotaFriendly: true,
    distanciaConduccionCorta: true,
    climaCalido: true,
  },
  {
    id: "toscana",
    nombre: "Toscana",
    pais: "Italia",
    paisCodigo: "IT",
    descripcion: "Colinas, vino, pueblos medievales y gastronomía de referencia mundial.",
    tags: ["gastronomia", "pueblos", "romantico", "naturaleza"],
    ritmo: ["tranquilo", "medio"],
    presupuestoDiaEstimado: { bajo: 80, medio: 150, alto: 260 },
    mascotaFriendly: false,
    distanciaConduccionCorta: true,
    climaCalido: true,
  },
  {
    id: "andalucia",
    nombre: "Andalucía",
    pais: "España",
    paisCodigo: "ES",
    descripcion: "Playa, ciudades monumentales, gastronomía y buena oferta familiar.",
    tags: ["playa", "gastronomia", "pueblos", "familiar", "ciudad"],
    ritmo: ["medio", "intenso"],
    presupuestoDiaEstimado: { bajo: 50, medio: 90, alto: 160 },
    mascotaFriendly: true,
    distanciaConduccionCorta: true,
    climaCalido: true,
  },
  {
    id: "costa-rica",
    nombre: "Costa Rica",
    pais: "Costa Rica",
    paisCodigo: "CR",
    descripcion: "Selva, volcanes, playas en dos océanos y turismo de aventura y naturaleza.",
    tags: ["naturaleza", "aventura", "playa"],
    ritmo: ["medio", "intenso"],
    presupuestoDiaEstimado: { bajo: 70, medio: 130, alto: 240 },
    mascotaFriendly: false,
    distanciaConduccionCorta: false,
    climaCalido: true,
  },
  {
    id: "marruecos",
    nombre: "Marruecos",
    pais: "Marruecos",
    paisCodigo: "MA",
    descripcion: "Mercados, desierto, montañas del Atlas y gastronomía muy marcada.",
    tags: ["aventura", "gastronomia", "pueblos", "ciudad"],
    ritmo: ["medio", "intenso"],
    presupuestoDiaEstimado: { bajo: 35, medio: 65, alto: 130 },
    mascotaFriendly: false,
    distanciaConduccionCorta: false,
    climaCalido: true,
  },
  {
    id: "tailandia",
    nombre: "Tailandia",
    pais: "Tailandia",
    paisCodigo: "TH",
    descripcion: "Playas, templos, gastronomía callejera y buena relación calidad-precio.",
    tags: ["playa", "aventura", "gastronomia"],
    ritmo: ["medio", "intenso"],
    presupuestoDiaEstimado: { bajo: 30, medio: 60, alto: 120 },
    mascotaFriendly: false,
    distanciaConduccionCorta: false,
    climaCalido: true,
  },
  {
    id: "islas-griegas",
    nombre: "Islas Griegas",
    pais: "Grecia",
    paisCodigo: "GR",
    descripcion: "Playas, pueblos blancos, buena gastronomía y ambiente romántico.",
    tags: ["playa", "romantico", "pueblos", "gastronomia"],
    ritmo: ["tranquilo", "medio"],
    presupuestoDiaEstimado: { bajo: 55, medio: 100, alto: 190 },
    mascotaFriendly: true,
    distanciaConduccionCorta: false,
    climaCalido: true,
  },
  {
    id: "colombia",
    nombre: "Colombia",
    pais: "Colombia",
    paisCodigo: "CO",
    descripcion: "Naturaleza diversa, playas en dos costas, ciudades coloniales y café.",
    tags: ["naturaleza", "aventura", "playa", "gastronomia", "ciudad"],
    ritmo: ["medio", "intenso"],
    presupuestoDiaEstimado: { bajo: 45, medio: 85, alto: 160 },
    mascotaFriendly: false,
    distanciaConduccionCorta: false,
    climaCalido: true,
  },
  {
    id: "japon",
    nombre: "Japón",
    pais: "Japón",
    paisCodigo: "JP",
    descripcion: "Ciudades ultramodernas, templos, gastronomía y una logística de tren excelente.",
    tags: ["ciudad", "gastronomia", "cultura"],
    ritmo: ["medio", "intenso"],
    presupuestoDiaEstimado: { bajo: 90, medio: 160, alto: 280 },
    mascotaFriendly: false,
    distanciaConduccionCorta: false,
    climaCalido: false,
  },
];

export function buscarDestinoPorId(id?: string): Destino | undefined {
  return DESTINOS.find((d) => d.id === id);
}

export function buscarDestinoPorNombre(nombre: string): Destino | undefined {
  const normalizado = nombre.trim().toLowerCase();
  return DESTINOS.find(
    (d) => d.nombre.toLowerCase() === normalizado || d.pais.toLowerCase() === normalizado
  );
}
