import type { BrainState } from "./brainState";
import type { CreativeAgentId, DesignLayer } from "./designSystemNeuron";

export type CreativeAuditSeverity = "critical" | "high" | "normal" | "polish";
export interface CreativeAuditFinding { id: string; agentId: CreativeAgentId; layer: DesignLayer; severity: CreativeAuditSeverity; surface: string; problem: string; evidence: string[]; recommendation: string; files: string[]; acceptanceCriteria: string[]; status: "open" | "verified"; }
export interface CreativeAuditReport { version: 1; auditedAt: string; surfaces: string[]; agents: CreativeAgentId[]; findings: CreativeAuditFinding[]; highestSeverity?: CreativeAuditSeverity; summary: string; }
export interface CreativeAuditInput { state: BrainState; sourceFiles?: Record<string, string>; }

const DEFAULT_SURFACES = ["src/app/page.tsx", "src/app/planificar/page.tsx", "src/app/cerebro/page.tsx", "src/app/viajes/[id]/page.tsx", "src/app/viajes/[id]/decisiones/page.tsx", "src/app/viajes/[id]/itinerario/page.tsx", "src/app/viajes/[id]/alojamiento/page.tsx", "src/app/viajes/[id]/transporte/page.tsx", "src/app/viajes/[id]/actividades/page.tsx", "src/components/", "src/app/globals.css"];
const AGENTS: CreativeAgentId[] = ["creative-director", "ux-strategist", "visual-designer", "color-psychology", "copy-strategist", "interaction-designer", "accessibility-designer", "responsive-designer", "motion-designer", "performance-designer", "design-system-engineer", "conversion-designer"];
const SEVERITY_RANK: Record<CreativeAuditSeverity, number> = { critical: 4, high: 3, normal: 2, polish: 1 };

function sourceText(sourceFiles: Record<string, string> | undefined, paths: string[]): string {
  if (!sourceFiles) return "";
  return Object.entries(sourceFiles).filter(([path]) => paths.some((requested) => requested.endsWith("/") ? path.startsWith(requested) : path === requested)).map(([, source]) => source).join("\n");
}
function finding(agentId: CreativeAgentId, layer: DesignLayer, severity: CreativeAuditSeverity, surface: string, problem: string, evidence: string[], recommendation: string, files: string[], acceptanceCriteria: string[], id: string): CreativeAuditFinding { return { id: `creative-audit:${id}`, agentId, layer, severity, surface, problem, evidence, recommendation, files, acceptanceCriteria, status: "open" }; }

function auditCreativeDirector(input: CreativeAuditInput): CreativeAuditFinding[] { const findings: CreativeAuditFinding[] = []; const homepage = input.sourceFiles?.["src/app/page.tsx"] ?? ""; if (/demo|ejemplo único/i.test(homepage)) findings.push(finding("creative-director", "brand", "high", "src/app/page.tsx", "La entrada principal todavía contiene posicionamiento de demostración.", ["El código contiene lenguaje de demo/ejemplo."], "Mantener la demo como prueba secundaria y dirigir la CTA principal al flujo real.", ["src/app/page.tsx"], ["La propuesta de valor se entiende sin conocer la arquitectura.", "La CTA primaria inicia el flujo real."], "homepage-demo-positioning")); if (input.state.blockers.length > 0 && !input.state.creativeDepartment) findings.push(finding("creative-director", "brand", "high", "brain-state", "El estado de bloqueo no tiene una capa creativa materializada.", [`Hay ${input.state.blockers.length} bloqueos en BrainState.`], "Representar bloqueo, espera y recuperación con lenguaje y semántica visual consistentes.", ["src/lib/travelBrain/presentation.ts", "src/components/"], ["Cada bloqueo relevante tiene explicación y siguiente acción."], "blocked-state-language")); return findings; }
function auditUx(input: CreativeAuditInput): CreativeAuditFinding[] { const source = sourceText(input.sourceFiles, ["src/app/cerebro/page.tsx", "src/app/planificar/page.tsx"]); if (!source || !/requirements|agents|cycles|orchestrator|provider/i.test(source)) return []; return [finding("ux-strategist", "content", "high", "src/app/cerebro/page.tsx", "Terminología interna puede filtrarse a la experiencia principal.", ["Se detectan referencias técnicas en la superficie."], "Mantener agentes, proveedores y métricas internas en Diagnóstico; Para ti debe mostrar significado, estado, decisión y acción.", ["src/app/cerebro/page.tsx"], ["Para ti no expone subsistemas.", "Diagnóstico conserva detalle técnico."], "traveler-view-internal-jargon")]; }
function auditVisual(input: CreativeAuditInput): CreativeAuditFinding[] { const source = sourceText(input.sourceFiles, ["src/app/", "src/components/"]); const count = (source.match(/\b(?:emerald|red|amber|green|yellow|orange)-(?:50|100|200|300|400|500|600|700|800|900)\b/g) ?? []).length; if (!source || count < 3) return []; return [finding("visual-designer", "visual", "high", "traveler surfaces", "Los estados funcionales usan colores utilitarios directos en varias superficies.", [`Se detectaron ${count} clases cromáticas directas.`], "Centralizar la semántica visual de estados y reutilizar patrones comunes.", ["src/app/", "src/components/", "src/app/globals.css"], ["Estados equivalentes comparten tokens.", "No hay color semántico arbitrario por pantalla."], "direct-status-colors")]; }
function auditColor(input: CreativeAuditInput): CreativeAuditFinding[] { const source = sourceText(input.sourceFiles, ["src/app/", "src/components/", "src/app/globals.css"]); if (!source || !/text-(?:red|green|amber|emerald)-|bg-(?:red|green|amber|emerald)-/i.test(source)) return []; return [finding("color-psychology", "psychology", "high", "state semantics", "La semántica de estado depende parcialmente de colores utilitarios directos.", ["Se encontraron clases de color de estado fuera de tokens semánticos."], "Usar roles success/warning/error/pending/verified acompañados de texto e icono.", ["src/app/globals.css", "src/lib/travelBrain/presentation.ts", "src/components/"], ["El estado sigue siendo comprensible sin color.", "Cada rol cromático tiene una función documentada."], "state-color-semantics")]; }
function auditCopy(input: CreativeAuditInput): CreativeAuditFinding[] { const source = sourceText(input.sourceFiles, ["src/app/", "src/components/"]); if (!source || !/orquestador|orchestrator|BrainState|BrainController|agentResults/i.test(source)) return []; return [finding("copy-strategist", "content", "high", "traveler-facing copy", "Hay vocabulario de infraestructura en superficies de usuario.", ["Se detectan términos internos en el código de UI."], "Traducir infraestructura a estados y consecuencias comprensibles para el viajero.", ["src/app/", "src/components/"], ["No aparece jerga interna en el flujo del viajero.", "Cada estado explica qué significa y qué puede hacer el usuario."], "traveler-copy")]; }
function auditInteraction(input: CreativeAuditInput): CreativeAuditFinding[] { const source = sourceText(input.sourceFiles, ["src/app/cerebro/page.tsx", "src/app/planificar/page.tsx", "src/components/"]); if (!source || !/(onClick|<button|<form|type=["']submit)/i.test(source) || /aria-|ariaLabel|aria-label/i.test(source)) return []; return [finding("interaction-designer", "interaction", "normal", "primary interactions", "No hay evidencia estática suficiente de una política de feedback accesible para interacciones críticas.", ["Existen controles interactivos sin evidencia ARIA en las fuentes auditadas."], "Definir feedback para idle/loading/success/partial/error/blocked y conservar el contexto.", ["src/app/cerebro/page.tsx", "src/app/planificar/page.tsx", "src/components/"], ["Cada acción crítica tiene feedback.", "Carga y error no pierden el contexto."], "interaction-feedback")]; }
function auditAccessibility(input: CreativeAuditInput): CreativeAuditFinding[] { const source = sourceText(input.sourceFiles, ["src/app/", "src/components/", "src/app/globals.css"]); if (!source || /prefers-reduced-motion|motion-reduce|aria-|ariaLabel|aria-label/i.test(source)) return []; return [finding("accessibility-designer", "accessibility", "high", "traveler surfaces", "No hay evidencia suficiente de una capa de accesibilidad explícita.", ["No se detectan reglas ARIA ni reduced-motion."], "Auditar nombres accesibles, foco, contraste, targets táctiles y reduced motion en componentes compartidos.", ["src/components/", "src/app/globals.css"], ["Controles críticos tienen nombre accesible.", "Focus visible está garantizado.", "Movimiento puede reducirse."], "accessibility-evidence")]; }
function auditResponsive(input: CreativeAuditInput): CreativeAuditFinding[] { const source = sourceText(input.sourceFiles, ["src/app/planificar/page.tsx", "src/app/cerebro/page.tsx"]); const count = (source.match(/grid-cols-|flex-row|w-full|max-w-|overflow-x/g) ?? []).length; if (!source || count <= 8) return []; return [finding("responsive-designer", "responsive", "normal", "planning and brain surfaces", "La densidad de layout merece una auditoría móvil específica.", [`Se detectaron ${count} decisiones de layout.`], "Priorizar acción principal, reducir densidad y verificar el flujo crítico en móvil.", ["src/app/planificar/page.tsx", "src/app/cerebro/page.tsx", "src/components/"], ["Flujo crítico usable con una mano.", "Sin scroll horizontal crítico."], "mobile-density")]; }
function auditMotion(input: CreativeAuditInput): CreativeAuditFinding[] { const source = sourceText(input.sourceFiles, ["src/app/", "src/components/", "src/app/globals.css"]); if (!source || !/animate-|transition-|duration-|keyframes/i.test(source) || /prefers-reduced-motion|motion-reduce/i.test(source)) return []; return [finding("motion-designer", "motion", "normal", "application surfaces", "Hay movimiento sin evidencia de soporte reduced-motion.", ["Se detectan utilidades de animación/transición sin regla reduced-motion."], "Aplicar una política global de reduced motion y limitar movimiento a feedback funcional.", ["src/app/globals.css", "src/components/"], ["prefers-reduced-motion reduce animaciones no esenciales."], "reduced-motion")]; }
function auditPerformance(input: CreativeAuditInput): CreativeAuditFinding[] { const source = sourceText(input.sourceFiles, ["src/app/", "src/components/"]); if (!source || !/<img\b/i.test(source) || /next\/image|\bImage\b/.test(source)) return []; return [finding("performance-designer", "performance", "normal", "application surfaces", "Hay imágenes sin evidencia de estrategia de optimización de Next.js.", ["Se detectan elementos <img>."], "Evaluar next/image donde corresponda sin añadir dependencias innecesarias.", ["src/app/", "src/components/"], ["Contenido crítico no queda bloqueado por assets secundarios."], "image-loading")]; }
function auditDesignSystem(input: CreativeAuditInput): CreativeAuditFinding[] { const source = sourceText(input.sourceFiles, ["src/app/globals.css", "src/components/"]); const count = (source.match(/#[0-9a-fA-F]{3,8}\b/g) ?? []).length; if (!source || count < 6) return []; return [finding("design-system-engineer", "implementation", "high", "design tokens", "Persisten suficientes valores cromáticos literales para justificar tokens semánticos.", [`Se detectaron ${count} valores hexadecimales.`], "Extraer valores recurrentes a tokens; conservar excepciones justificadas.", ["src/app/globals.css", "src/components/"], ["Estados equivalentes comparten tokens.", "Una corrección visual puede aplicarse de forma consistente."], "design-tokens")]; }
function auditConversion(input: CreativeAuditInput): CreativeAuditFinding[] { const source = sourceText(input.sourceFiles, ["src/app/page.tsx", "src/app/planificar/page.tsx"]); const ctas = (source.match(/<button|<a\b|<Link\b/gi) ?? []).length; if (!source || ctas < 4) return []; return [finding("conversion-designer", "interaction", "normal", "entry and planning", "La entrada contiene varias acciones potenciales y necesita jerarquía explícita.", [`Se detectaron aproximadamente ${ctas} elementos de acción/enlace.`], "Definir una CTA primaria por estado y hacer progresivas las acciones secundarias.", ["src/app/page.tsx", "src/app/planificar/page.tsx"], ["La acción principal es inequívoca.", "Las acciones secundarias no compiten visualmente."], "cta-hierarchy")]; }

export function auditCreativeAgents(input: CreativeAuditInput): CreativeAuditReport {
  const findings = [...auditCreativeDirector(input), ...auditUx(input), ...auditVisual(input), ...auditColor(input), ...auditCopy(input), ...auditInteraction(input), ...auditAccessibility(input), ...auditResponsive(input), ...auditMotion(input), ...auditPerformance(input), ...auditDesignSystem(input), ...auditConversion(input)].sort((a, b) => SEVERITY_RANK[b.severity] - SEVERITY_RANK[a.severity]);
  const surfaces = Object.keys(input.sourceFiles ?? {}).length ? Object.keys(input.sourceFiles ?? {}).sort() : DEFAULT_SURFACES;
  const highestSeverity = findings[0]?.severity;
  return { version: 1, auditedAt: new Date().toISOString(), surfaces, agents: AGENTS, findings, highestSeverity, summary: findings.length ? `${findings.length} hallazgos creativos abiertos; prioridad máxima: ${highestSeverity}.` : "No se encontraron hallazgos con las reglas activas en las fuentes proporcionadas." };
}
