import type { BrainState } from "./brainState";

export type DesignLayer = "brand" | "psychology" | "content" | "interaction" | "visual" | "component" | "responsive" | "accessibility" | "motion" | "performance" | "implementation";
export type CreativeAgentId = "creative-director" | "ux-strategist" | "visual-designer" | "color-psychology" | "copy-strategist" | "interaction-designer" | "accessibility-designer" | "responsive-designer" | "motion-designer" | "performance-designer" | "design-system-engineer" | "conversion-designer";
export interface DesignInstruction { id: string; layer: DesignLayer; agentId: CreativeAgentId; priority: "critical" | "high" | "normal" | "polish"; objective: string; commands: string[]; libraries: string[]; files: string[]; acceptanceCriteria: string[]; }
export interface CreativeAgentSpec { id: CreativeAgentId; department: "creative" | "product" | "engineering"; responsibility: string; inputs: string[]; outputs: string[]; constraints: string[]; }
export interface DesignSystemBrief { version: 1; principle: string; layers: DesignLayer[]; agents: CreativeAgentSpec[]; instructions: DesignInstruction[]; colorPsychology: { primaryRole: string; accentRole: string; warningRole: string; successRole: string; rules: string[] }; commandPolicy: string[]; libraryPolicy: string[]; }

const AGENTS: CreativeAgentSpec[] = [
  ["creative-director","creative","Coherencia de marca y experiencia","brand"], ["ux-strategist","product","Arquitectura de información y decisiones","journey"], ["visual-designer","creative","Jerarquía visual, composición y tipografía","visual"], ["color-psychology","creative","Roles semánticos de color y contraste","state"], ["copy-strategist","creative","Lenguaje humano, estados y microcopy","copy"], ["interaction-designer","product","Estados, controles y recuperación","interaction"], ["accessibility-designer","product","Accesibilidad perceptiva, motora y cognitiva","a11y"], ["responsive-designer","product","Experiencia móvil, tablet y escritorio","responsive"], ["motion-designer","creative","Movimiento funcional y reduced motion","motion"], ["performance-designer","engineering","Velocidad, estabilidad y peso visual","performance"], ["design-system-engineer","engineering","Tokens, componentes y patrones reutilizables","implementation"], ["conversion-designer","product","Comprensión, confianza y siguiente acción","conversion"],
].map(([id, department, responsibility, input]) => ({ id: id as CreativeAgentId, department: department as CreativeAgentSpec["department"], responsibility, inputs: [input, "brain_state"], outputs: ["rules", "priorities", "implementation"], constraints: ["No inventar capacidades", "Priorizar claridad", "No depender sólo del color"] }));

const layerOwners: Record<DesignLayer, CreativeAgentId> = { brand: "creative-director", psychology: "color-psychology", content: "copy-strategist", interaction: "interaction-designer", visual: "visual-designer", component: "design-system-engineer", responsive: "responsive-designer", accessibility: "accessibility-designer", motion: "motion-designer", performance: "performance-designer", implementation: "design-system-engineer" };

function instruction(layer: DesignLayer, objective: string, files: string[], priority: DesignInstruction["priority"] = "high"): DesignInstruction { return { id: `layer:${layer}`, layer, agentId: layerOwners[layer], priority, objective, commands: ["auditar estado actual", "aplicar cambios mínimos y trazables", "verificar criterios de aceptación"], libraries: ["React", "Next.js", "Tailwind/CSS existente"], files, acceptanceCriteria: ["El usuario entiende el estado", "No se inventan capacidades", "El resultado es verificable"] }; }

export function buildDesignSystemBrief(_state: BrainState): DesignSystemBrief {
  const layers: DesignLayer[] = ["brand", "psychology", "content", "interaction", "visual", "component", "responsive", "accessibility", "motion", "performance", "implementation"];
  const instructions: DesignInstruction[] = [
    instruction("brand", "Mantener una identidad reconocible y coherente en todas las superficies.", ["src/app/page.tsx", "src/app/planificar/page.tsx", "src/app/cerebro/page.tsx"], "critical"),
    instruction("psychology", "Usar color para orientar atención y estado sin manipular ni excluir.", ["src/app/globals.css", "src/lib/travelBrain/presentation.ts"], "critical"),
    instruction("content", "Convertir estados técnicos en lenguaje humano orientado a decisión.", ["src/app/page.tsx", "src/app/planificar/page.tsx", "src/app/cerebro/page.tsx"], "critical"),
    instruction("interaction", "Dar una respuesta de interfaz a cada estado del cerebro y conservar contexto.", ["src/app/cerebro/page.tsx", "src/app/planificar/page.tsx", "src/app/viajes/[id]/"], "critical"),
    instruction("visual", "Crear jerarquía visual clara sin densidad innecesaria.", ["src/components/", "src/app/"], "high"),
    instruction("component", "Centralizar patrones de estado, CTA y feedback reutilizables.", ["src/components/", "src/lib/travelBrain/presentation.ts"], "high"),
    instruction("responsive", "Priorizar el contexto móvil real del viajero y evitar scroll horizontal crítico.", ["src/app/", "src/components/"], "high"),
    instruction("accessibility", "Garantizar nombres accesibles, contraste, foco, targets y reduced motion.", ["src/app/globals.css", "src/components/"], "high"),
    instruction("motion", "Usar movimiento sólo para orientar y confirmar cambios de estado.", ["src/app/globals.css", "src/components/"], "normal"),
    instruction("performance", "Evitar que la inteligencia y el diseño perjudiquen velocidad y estabilidad.", ["src/app/", "src/components/", "package.json"], "high"),
    instruction("implementation", "Convertir las reglas creativas en tokens y componentes trazables.", ["src/components/", "src/app/globals.css"], "high"),
  ];
  return { version: 1, principle: "Diseñar desde el significado del estado del cerebro, no decorar una arquitectura técnica.", layers, agents: AGENTS, instructions, colorPsychology: { primaryRole: "Orientación y acción principal.", accentRole: "Oportunidades y acciones secundarias.", warningRole: "Atención o incertidumbre, siempre con texto/icono.", successRole: "Sólo evidencia validada o tarea completada.", rules: ["No usar rojo para todo lo pendiente.", "No usar verde para todo lo que el sistema cree correcto.", "Nunca codificar un estado sólo mediante color.", "Mantener contraste suficiente."] }, commandPolicy: ["Preferir componentes y CSS existentes.", "Toda instrucción debe traducirse a cambios verificables.", "No usar comandos destructivos sin alcance explícito."], libraryPolicy: ["No añadir dependencias por defecto.", "Reutilizar React, Next.js y Tailwind existentes.", "Una dependencia nueva debe resolver una necesidad demostrable."] };
}
